don't parse eval URLs after captureJSCallUsage. parse all others.
wardpeet/lighthouse pull request #2
Opened 2016-12-13 18:31 UTC by paulirish

This PR's destination is PR #997 (Add whatwg-url parser to parse our urls)

The unit tests provide nonparsable urls that appear to come from `eval()` however they were tagged as `isEval: false`, which doesn't make sense.

I think we can trust the V8 Stack Trace API to correctly tag the `isEval` property, so i've adjusted those test fixtures. This allows us to nuke the ugly try/catch on parsing.

@ebidel does this work for you?

2016-12-13 18:33 UTC, paulirish commented on lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
> +  new Function('Date.now()')() // FAIL
added this for coverage though it didnt appear to hit any assertions. ¯\_(ツ)_/¯

2016-12-13 18:34 UTC, paulirish commented
To be clear, the try/catch was added by ward. This PR reverts those bits to what was there, except swapping out `url.parse` for `new URL`. `url.parse` didn't throw.

2016-12-13 18:41 UTC, brendankenny commented on lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.html
> +  new Function('Date.now()')() // FAIL
I believe thats because smokehouse is only checking true/false right now. Need googlechrome/lighthouse/issues/964

2016-12-13 18:45 UTC, brendankenny requested changes

2016-12-13 18:45 UTC, brendankenny commented on lighthouse-core/audits/dobetterweb/no-console-time.js
> +      return err.isEval ? err.url : new URL(err.url).host === pageHost;
shouldn't this be `!!err.url` to also be boolean? @ebidel since this was in the original

2016-12-13 18:45 UTC, brendankenny commented on lighthouse-core/audits/dobetterweb/no-datenow.js
> +      return err.isEval ? err.url : new URL(err.url).host === pageHost;
same here

2016-12-13 20:05 UTC, paulirish commented on lighthouse-core/audits/dobetterweb/no-console-time.js
> +      return err.isEval ? err.url : new URL(err.url).host === pageHost;
happy to cast to boolean to make it more obvious it's being used for the filter fn.

2016-12-13 20:13 UTC, brendankenny commented on lighthouse-core/audits/dobetterweb/no-console-time.js
> +      return err.isEval ? err.url : new URL(err.url).host === pageHost;
oh, it's for `filter`...somehow missed that :)

2016-12-13 20:14 UTC, brendankenny approved these changes
LGTM FWIW

2016-12-13 20:16 UTC, ebidel approved these changes

2016-12-13 20:32 UTC, paulirish commented
@wardpeet you'll have to merge. :)

2016-12-14 09:46 UTC, merged

2016-12-14 09:46 UTC, wardpeet commented
@paulirish done :)